# Generated by Django 3.2.5 on 2021-08-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimages',
            options={'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.RemoveField(
            model_name='galleryimages',
            name='image_url',
        ),
    ]
