# Generated by Django 3.2.5 on 2021-08-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210823_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='order_number',
            field=models.CharField(max_length=254),
        ),
    ]
