# Generated by Django 3.2.5 on 2021-08-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prep_time',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=2),
            preserve_default=False,
        ),
    ]
