# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Read '.env' file created for Testing Parameters stored in Project Root
import environ
import os
root = environ.Path(__file__) - 3  # get root of the project
env = environ.Env()
environ.Env.read_env()  # reading .env file

class TestUserProfiles():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1CreateaUserProfile(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "user-text").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys("tester1@tester1.com")
    self.driver.find_element(By.ID, "id_email").send_keys("tester1@tester1.com")
    self.driver.find_element(By.ID, "id_email").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "id_email2").click()
    self.driver.find_element(By.ID, "id_email2").send_keys("tester1@tester1.com")
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("tester1")
    self.driver.find_element(By.ID, "id_password1").click()
    self.driver.find_element(By.ID, "id_password1").send_keys("qazWSX3dc")
    self.driver.find_element(By.ID, "id_password2").click()
    self.driver.find_element(By.ID, "id_password2").send_keys("qazWSX3dc")
    self.driver.find_element(By.ID, "submit").click()
  
  def test_2Logginginwithaverifiedaccount(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "user-text").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "id_login").click()
    self.driver.find_element(By.ID, "id_login").send_keys("Aramantos")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("qazWSX3dc")
    self.driver.find_element(By.ID, "sign-in-button").click()
    self.driver.find_element(By.CSS_SELECTOR, "span").click()
  
  def test_3LoggingoutofaUserProfile(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.find_element(By.ID, "sign-out").click()
  
