# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreatinganOrder():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1Addingaproducttothebasket(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "open-closed").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-sm-6:nth-child(1) .card-img-top").click()
    self.driver.find_element(By.ID, "add-basket").click()
  
  def test_2Updatingthequantityofaproductinthebasket(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "basket-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".py-3 #increment-qty_2 .fas").click()
    self.driver.find_element(By.LINK_TEXT, "Update").click()
  
  def test_3Removingaproductfromthebasket(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "basket-text").click()
    self.driver.find_element(By.LINK_TEXT, "Remove").click()
  
  def test_4Takingabaskettothecheckoutpage(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "basket").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > #checkout > .text-uppercase").click()
  
  def test_5Fillingouttheformandpaymentdetailstoprocessanorder(self):
    self.driver.get("TEST_LINK")
    self.driver.set_window_size(1439, 1017)
    self.driver.find_element(By.ID, "basket-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > #checkout > .text-uppercase").click()
    self.driver.find_element(By.ID, "id_full_name").click()
    self.driver.find_element(By.ID, "id_full_name").send_keys("ORDER_NAME")
    self.driver.find_element(By.ID, "id_email").send_keys("ORDER_EMAIL)
    self.driver.find_element(By.ID, "id_phone_number").send_keys("ORDER_PHONE_NUMBER")
    self.driver.find_element(By.ID, "id_street_address1").send_keys("ORDER_ADDRESS1")
    self.driver.find_element(By.ID, "id_street_address2").send_keys("ORDER_ADDRESS2")
    self.driver.find_element(By.ID, "id_town_or_city").send_keys("ORDER_TOWN_CITY)
    self.driver.find_element(By.ID, "id_postcode").send_keys("ORDER_POSTCODE")
    self.driver.find_element(By.ID, "id_county").send_keys("ORDER_COUNTY")
    self.driver.find_element(By.ID, "card-element").click()
    self.driver.switch_to.frame(1)
    self.driver.find_element(By.NAME, "cardnumber").click()
    self.driver.find_element(By.NAME, "cardnumber").send_keys("4242 4242 4242 4242")
    self.driver.find_element(By.NAME, "exp-date").send_keys("04 / 24")
    self.driver.find_element(By.NAME, "cvc").send_keys("242")
    self.driver.find_element(By.NAME, "postal").send_keys("42424")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, "#submit-button > .font-weight-bold").click()
  
